version: "3.5"

services:
  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hbase-standalone.env
    networks:
      cscourse:

networks:
  cscourse:
    name: hadoop

volumes:
  hbase_data:
  hbase_zookeeper_data:
